# Generated by Django 5.2.7 on 2025-10-05 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "film_title",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                        verbose_name="Название фильма",
                    ),
                ),
                (
                    "film_description",
                    models.CharField(
                        max_length=250,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name="Описание фильма",
                    ),
                ),
                ("review_text", models.TextField(verbose_name="Отзыв")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
    ]
