# Generated by Django 5.2.7 on 2025-10-06 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0003_add_review_text_field"),
        ("films", "0003_rename_review_text_field"),
    ]

    operations = []
